

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    environment:
      - ENV=development
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - ENV=development
    depends_on:
      - backend
      - mongodb


  mongodb:
    image: mongo:latest
    container_name: local-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: resume_reviewer
    command: mongod
    restart: unless-stopped

volumes:
  mongo-data:
  # Uncomment the following lines if you want to use a custom network
  # custom-network:
  #   driver: bridge
  


